#!/usr/bin/env bash

set -ex

YARN_BIN=$(which yarn)

# REPOSITORY_URL: URL to the Git repository the build pulls changes from.
# BRANCH: Reference to check out after fetching changes from the Git repository.
# PULL_REQUEST: Whether the build is from a pull request or not.
# HEAD: Name of the head branch received from a Git provider.
# COMMIT_REF: Reference of the commit we’re building.
# CONTEXT: Name of the context a deploy is built around, it can be production, deploy-preview or branch-deploy.
# URL: This URL represents the main address to your site. It can be either a netlify subdomain or your own custom domain if you set one. For example, https://example.netlify.com or https://www.example.com.
# DEPLOY_URL: This URL represents the unique URL for an individual deploy. It starts with a unique ID that identifies the deploy. For example, https://578ab634d6865d5cf960d620--open-api.netlify.com.
# DEPLOY_PRIME_URL: This URL represents the primary URL for an individual deploy, or a group of them, like branch deploys and deploy previews. For example, https://deploy-preview-34--open-api.netlify.com or https://beta--open-api.netlify.com.

echo 'Mapping Netlify build env vars to create-react-app, and running build ...'

REACT_APP_REPOSITORY_URL="$REPOSITORY_URL" \
REACT_APP_BRANCH="$BRANCH" \
REACT_APP_PULL_REQUEST="$PULL_REQUEST" \
REACT_APP_HEAD="$HEAD" \
REACT_APP_COMMIT_REF="$COMMIT_REF" \
REACT_APP_CONTEXT="$CONTEXT" \
REACT_APP_URL="$URL" \
REACT_APP_DEPLOY_URL="$DEPLOY_URL" \
REACT_APP_DEPLOY_PRIME_URL="$DEPLOY_PRIME_URL" \
$YARN_BIN build "$@"
